<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd">

	<bean name="myDs" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
		<property name="url" value="jdbc:hsql:localdb" />
	</bean>

	<bean name="txAwareDXProxy" class="org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy">
		<property name="targetDataSource" ref="myDs"/>
	</bean>

	<bean id="sessionFactory" class="org.springframework.orm.hibernate3.LocalSessionFactoryBean" lazy-init="true">
		<property name="dataSource" ref="myDs"/>
		<property name="hibernateProperties">
			<props>
				<prop key="hibernate.dialect">dialect.that.doesnt.exist.and.should.be.auto_replaced</prop>
				<prop key="hibernate.show_sql">true</prop>
				<prop key="hibernate.generate_statistics">false</prop>
				<!--  To avoid connecting to database during testing -->
				<prop key="hibernate.temp.use_jdbc_metadata_defaults">false</prop>
			</props>
		</property>
	</bean>

	<!-- Instantiates the FakeFactoryBean, which will cause an Exception if
		our bean scan is prematurely instantiating FactoryBeans (allowEagerInit=true) -->
	<context:component-scan base-package="org.cloudfoundry.reconfiguration.test" />

</beans>
